
print ("integer equals :")
print ("B:" , ord ('B'))
print ("C:" , ord ('C'))
print ("D:" , ord ('D'))
print ("b:" , ord ('b'))
print ("c:" , ord ('c'))
print ("d:" , ord ('d'))
print ("0:" , ord ('0'))
print ("1:" , ord ('1'))
print ("2:" , ord ('2'))
print ("$:", ord ('$'))
print ("*:" , ord ('*'))
print ("+:" , ord ('+'))
print ("Space:" , ord ('%'))
